name: Create Dummy Pull Request

on:
  issues:
    types:
      - opened

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create changes
        run: |
          date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: wakamsha-bot <wakamsha-bot@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Example] Update report'
          draft: false
